# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'onekins' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for onekins

  target 'onekinsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'onekinsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'

end
